---
- name: configure ufw
  hosts: ubuntu
  become: yes
  tasks:
    - name: Open 80 port ufw
      ansible.builtin.ufw:
        rule: allow
        port: 80
        proto: tcp
        
- name: configure firewalld
  hosts: fedora
  become: yes
  tasks:
    - name: Open 80 port firewalld
      ansible.builtin.firewalld:
        port: 80/tcp
        permanent: yes
        state: enabled
        immediate: yes
